var full_name = "John Doe";
var email = "JohnDoe@gmail.com";
var tel = "6479108765";
var address = "123 Street Street";
var unit = "321";
var zip = "M9J3J9";
var city = "TORONTO";
var country = "CANADA";
var state = "ON";

document.getElementById('order_billing_name').value = full_name;
document.getElementById('order_email').value = email;
document.getElementById('order_tel').value = tel;
document.getElementById('bo').value = address;
document.getElementById('oba3').value = unit;
document.getElementById('order_billing_zip').value = zip;
document.getElementById('order_billing_city').value = city;
document.getElementById('order_billing_country').value = country;
document.getElementById('order_billing_state').value = state;
